version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/composite-orgs-transformer
    docker:
      - image: golang:1.8.3
        environment:
          GOPATH: /go
          CIRCLE_TEST_REPORTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: External Dependencies
          command: |
            go get -u github.com/mattn/goveralls
            go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Test Results
          command: |
            mkdir -p ${CIRCLE_TEST_REPORTS}
      - run:
          name: Go Get
          command: go get -t -d -v ./...
      - run:
          name: Go Build
          command: go build -v
      - run:
          name: Run Tests
          command: |
            go test -race -v ./... | /go/bin/go-junit-report > ${CIRCLE_TEST_REPORTS}/main.xml
      - store_test_results:
          path: /tmp/test-results
  dockerfile:
    working_directory: /composite-orgs-transformer
    docker:
      - image: docker:18.03
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .
workflows:
  version: 2
  test-and-build-docker:
    jobs:
      - build
      - dockerfile:
          requires:
            - build
